name: area-breakdown

inputs:
  - signoff.area.rpt

outputs:
  - area_breakdown.json

commands:
  - python area_plot.py
  - cp area_breakdown.json outputs/
  - python canonicalizer.py
  - mv tile_area.json area_E.json

parameters:
  design_name: TileStatic__80f6b2a8da51c510
