#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

dist: xenial
language: python
# Use pypy3.6-7.0.0 to have 1.12.0 version of CFFI which has `dlclose`
python:
 - "3.6"
 - "3.7"
 - "pypy3.6-7.0.0"

env:
 - CONFIG=""
 #- CONFIG="--test-verilog"
 # - CONFIG="--dump-vcd"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:

 # Install packages
 - sudo apt-get install -y graphviz

 # Install verilator
 - wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.008.tar.gz
 - tar -C ${HOME} -xzf verilator-travis-4.008.tar.gz
 - export VERILATOR_ROOT=${HOME}/verilator
 - export PATH=${VERILATOR_ROOT}/bin:${PATH}
 - export PYMTL_VERILATOR_INCLUDE_DIR=${VERILATOR_ROOT}/share/verilator/include
 - verilator --version

 # Install Python requirements
 - pip install --upgrade pip setuptools twine
 - pip install --requirement requirements.txt
 - pip install .
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - autoflake --recursive --in-place --remove-duplicate-keys .
 - pyupgrade --py3-only --keep-percent-format $(find . -name '*.py')
 - isort --apply --recursive ./pymtl3
 - flake8 --select=F --ignore=F401,F405,F403,F811,F821,F841
 - git diff --exit-code
 - mkdir -p build
 - cd build
 - py.test --cov-report xml --cov=pymtl3 ../pymtl3 $CONFIG

#-------------------------------------------------------------------------
# after success
#-------------------------------------------------------------------------

after_success:
  - codecov
