name: synopsys-ptpx-rtl

inputs:
  - adk
  - design.vcs.v
  - design.spef.gz
  - design.pt.sdc
  - run.saif
  - design.namemap

outputs:
  - reports

commands:
  - pt_shell -file pt_px.tcl
  - cp -aL reports outputs/

parameters:
  sim_clock_period: 5.00
  design_name: undefined
